version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      dev-tooling:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript*'
          - 'prettier*'
          - 'vitest*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
